`gui_apps`: ITerm extensions

diff --git a/etc/init.d/gui_apps b/etc/init.d/gui_apps
--- a/etc/init.d/gui_apps
+++ b/etc/init.d/gui_apps
@@ -196,8 +196,6 @@ start() {
 				mount -o remount,ro "${extension_mountpoint}/dev" || die "Failed to remount '${extension_mountpoint}/dev' read-only." 1
 				## mnt
 				(mkdir -p "${extension_mountpoint}/mnt/onboard/.kobo" && echo "$(cat /opt/inkbox_device | tr [:lower:] [:upper:])" > "${extension_mountpoint}/mnt/onboard/.kobo/version" && mount -o remount,ro "${extension_mountpoint}/mnt") || die "Failed to set up fake onboard filesystem for FBInk." 1
-				## User data
-				(mount --bind "${extension_userdata_path}" "${extension_mountpoint}/app-data" && chown user:user "${extension_mountpoint}/app-data") || die "Failed to bind-mount user data directory '${extension_userdata_path}' at '${extension_mountpoint}/app-data'." 1
 				## Time zone
 				# Mount from gui because inkbox_gui script manages config files for it
 				bind_mount_wrapper "/usr/share/zoneinfo/" "gui"
@@ -205,6 +203,28 @@ start() {
 				mount --bind "/kobo/etc/localtime" "${extension_mountpoint}/etc/localtime"
 				## Restrict /etc
 				(mount -o remount,ro "${extension_mountpoint}/etc") || die "Failed to remount '${extension_mountpoint}/etc' read-only." 1
+
+				## ITerm
+				if [ "${extension_name}" == "ITerm" ]; then
+					iterm_extensions_path="${extension_userdata_path}/extensions"
+					if [ "$(ls -A ""${iterm_extensions_path}"")" ]; then
+						for iterm_extension in ${iterm_extensions_path}/*; do
+							if [ "${iterm_extension}" != "${iterm_extensions_path}/*" ]; then
+								iterm_extension_path="${iterm_extension}"
+								iterm_extension_mountpoint="${iterm_extensions_path}/$(basename -s '.isa' ""${iterm_extension}"")"
+								if [ -f "${iterm_extension_path}" ]; then
+									mkdir -p "${iterm_extension_mountpoint}"
+									squashfuse -o allow_other,nosuid,nodev "${iterm_extension_path}" "${iterm_extension_mountpoint}"
+								fi
+							else
+								continue
+							fi
+						done
+					fi
+				fi
+
+				## User data
+				(mount --rbind "${extension_userdata_path}" "${extension_mountpoint}/app-data" && chown user:user "${extension_mountpoint}/app-data") || die "Failed to bind-mount user data directory '${extension_userdata_path}' at '${extension_mountpoint}/app-data'." 1
 
 				einfo "Successfully set up application '${extension_name}'"
 			else
@@ -247,8 +267,17 @@ die() {
 
 stop() {
 	sync
+
+	umount -l -f /kobo/mnt/onboard/onboard/.apps-data/*/* 2>/dev/null
+	umount -l -f /kobo/mnt/onboard/onboard/.apps-data/ITerm/extensions/* 2>/dev/null
 	umount -l -f /kobo/mnt/onboard/onboard/.apps/*/* 2>/dev/null
+
+	umount -l -f /kobo/external_root/data/onboard/.apps-data/*/* 2>/dev/null
+	umount -l -f /kobo/external_root/data/onboard/.apps-data/ITerm/extensions/* 2>/dev/null
 	umount -l -f /kobo/external_root/data/onboard/.apps/*/* 2>/dev/null
+
+	umount -l -f /data/onboard/.apps-data/*/* 2>/dev/null
+	umount -l -f /data/onboard/.apps-data/ITerm/extensions/* 2>/dev/null
 	umount -l -f /data/onboard/.apps/*/* 2>/dev/null
 	return 0
 }
